name: aethero
description: "A weather-based training planner."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  go_router: ^17.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  lucide_flutter: ^1.7.0
  flutter_svg: ^2.2.3
  hive_ce: ^2.2.3
  hive_ce_flutter: ^1.1.0
  hive_ce_generator: ^1.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/aetheroAppIcon.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/aetheroAppIcon.png"
  adaptive_icon_background: "#FFFFFF"
