// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:aethero/features/search/domain/entities/city.dart';
import 'package:aethero/features/weather/domain/entities/hourly_weather.dart';
import 'package:aethero/features/weather/domain/entities/weather.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CityAdapter());
    registerAdapter(HourlyWeatherAdapter());
    registerAdapter(WeatherAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CityAdapter());
    registerAdapter(HourlyWeatherAdapter());
    registerAdapter(WeatherAdapter());
  }
}
